/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "netatmo-crawler adapter settings": {
        en: "Adapter settings for netatmo-crawler",
        de: "Adaptereinstellungen für netatmo-crawler",
        ru: "Настройки адаптера для netatmo-crawler",
        pt: "Configurações do adaptador para netatmo-crawler",
        nl: "Adapterinstellingen voor netatmo-crawler",
        fr: "Paramètres d'adaptateur pour netatmo-crawler",
        it: "Impostazioni dell'adattatore per netatmo-crawler",
        es: "Ajustes del adaptador para netatmo-crawler",
        pl: "Ustawienia adaptera dla netatmo-crawler",
        "zh-cn": "netatmo-crawler的适配器设置",
    },
    station1: {
        en: "Enter the url to the Netatmo Station you want to get information from.",
        de: "Geben Sie die URL der Netatmo Station ein, von der Sie Informationen erhalten möchten.",
        ru: "Введите URL-адрес станции Netatmo, с которой вы хотите получить информацию.",
        pt: "Digite o URL da estação Netatmo da qual você deseja obter informações.",
        nl: "Voer de url in naar het Netatmo Station waar u informatie van wilt krijgen.",
        fr: "Saisissez l'URL de la station Netatmo à partir de laquelle vous souhaitez obtenir des informations.",
        it: "Immettere l'URL della Netatmo Station da cui si desidera ottenere informazioni.",
        es: "Ingrese la url de la estación de Netatmo de la que desea obtener información.",
        pl: "Wpisz adres URL stacji Netatmo, z której chcesz uzyskać informacje.",
        "zh-cn": "输入要从中获取信息的Netatmo Station的URL。",
    },
    station2: {
        en: "Addional url for another station. Can be empty.",
        de: "Zusätzliche URL für eine andere Station. ",
        ru: "Дополнительный URL для другой станции. ",
        pt: "URL adicional para outra estação. ",
        nl: "Extra URL voor een ander station. ",
        fr: "URL supplémentaire pour une autre station. ",
        it: "URL aggiuntivo per un'altra stazione. ",
        es: "URL adicional para otra estación. ",
        pl: "Dodatkowy adres URL innej stacji. ",
        "zh-cn": "另一个站点的附加URL。",
    },
    station3: {
        en: "Addional url for another station. Can be empty.",
        de: "Zusätzliche URL für eine andere Station. ",
        ru: "Дополнительный URL для другой станции. ",
        pt: "URL adicional para outra estação. ",
        nl: "Extra URL voor een ander station. ",
        fr: "URL supplémentaire pour une autre station. ",
        it: "URL aggiuntivo per un'altra stazione. ",
        es: "URL adicional para otra estación. ",
        pl: "Dodatkowy adres URL innej stacji. ",
        "zh-cn": "另一个站点的附加URL。",
    },
    station4: {
        en: "Addional url for another station. Can be empty.",
        de: "Zusätzliche URL für eine andere Station. ",
        ru: "Дополнительный URL для другой станции. ",
        pt: "URL adicional para outra estação. ",
        nl: "Extra URL voor een ander station. ",
        fr: "URL supplémentaire pour une autre station. ",
        it: "URL aggiuntivo per un'altra stazione. ",
        es: "URL adicional para otra estación. ",
        pl: "Dodatkowy adres URL innej stacji. ",
        "zh-cn": "另一个站点的附加URL。",
    },
};