/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "netatmo-crawler adapter settings": {            "en": "Adapter settings for netatmo-crawler",            "de": "Adaptereinstellungen für Netatmo-Crawler",        "ru": "Настройки адаптера для netatmo-crawler",          "pt": "Configurações do adaptador para netatmo-crawler", "nl": "Adapterinstellingen voor netatmo-crawler",        "fr": "Paramètres de l'adaptateur pour netatmo-crawler", "it": "Impostazioni dell'adattatore per netatmo-crawler", "es": "Ajustes del adaptador para netatmo-crawler",      "pl": "Ustawienia adaptera dla robota sieciowego Netatmo", "zh-cn": "netatmo-crawler的适配器设置"},
    "stationNameType": {                             "en": "Select how the objects for each station should named", "de": "Wählen Sie aus, wie die Objekte für jede Station benannt werden sollen", "ru": "Выберите, как объекты для каждой станции должны быть названы", "pt": "Selecione como os objetos para cada estação devem nomear", "nl": "Selecteer hoe de objecten voor elk station een naam moeten krijgen", "fr": "Sélectionnez le nom des objets de chaque station", "it": "Seleziona il nome degli oggetti per ciascuna stazione", "es": "Seleccione cómo deben nombrarse los objetos para cada estación", "pl": "Wybierz, jak mają być nazywane obiekty dla każdej stacji", "zh-cn": "选择每个工作站的对象应如何命名"},
    "stationNameTypeCounter": {                      "en": "Use Counter, e.g. 1",                             "de": "Zähler verwenden, z.B. 1",                        "ru": "Используйте счетчик, например 1",                 "pt": "Use o contador, p. 1",                            "nl": "Gebruik teller, b.v. 1",                          "fr": "Utilisez Counter, par ex. 1",                     "it": "Usa contatore, ad es. 1",                         "es": "Usar contador, p. 1",                             "pl": "Użyj licznika, np. 1",                            "zh-cn": "使用计数器，例如1个"},
    "stationNameTypeId": {                           "en": "Use the id of the station, e.g. 70:3f:ee:7c:37:6c", "de": "Verwenden Sie die ID der Station, z.B. 70: 3f: ee: 7c: 37: 6c", "ru": "Используйте идентификатор станции, например, 70: 3f: й: 7в: 37: 6c", "pt": "Use o ID da estação, por exemplo 70: 3f: ee: 7c: 37: 6c", "nl": "Gebruik de id van het station, b.v. 70: 3f: ee: 7c: 37: 6c", "fr": "Utilisez l'identifiant de la station, par ex. 70: 3f: ee: 7c: 37: 6c", "it": "Usa l'id della stazione, ad es. 70: 3f: ee: 7c: 37: 6c", "es": "Use la identificación de la estación, p. 70: 3f: ee: 7c: 37: 6c", "pl": "Użyj identyfikatora stacji, np. 70: 3f: ee: 7c: 37: 6c", "zh-cn": "使用电台的ID，例如70：3f：ee：7c：37：6c"},
    "stationUrls": {                                 "en": "Enter the urls for the stations. You can enter multiple stations. One per line", "de": "Geben Sie die URLs für die Stationen ein. Sie können mehrere Stationen eingeben. Eine pro Zeile", "ru": "Введите URL для станций. Вы можете ввести несколько станций. Один на линию", "pt": "Digite os URLs para as estações. Você pode inserir várias estações. Um por linha", "nl": "Voer de URL's van de stations in. U kunt meerdere stations invoeren. Een per regel", "fr": "Saisissez les URL des stations. Vous pouvez entrer plusieurs stations. Un par ligne", "it": "Inserisci gli URL per le stazioni. È possibile inserire più stazioni. Uno per riga", "es": "Ingrese las URL de las estaciones. Puedes ingresar múltiples estaciones. Una por línea", "pl": "Wpisz adresy URL stacji. Możesz wprowadzić wiele stacji. Jeden na linię", "zh-cn": "输入工作站的URL。您可以输入多个电台。每行一个"},
};